In [1]:
# 🤖 Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import streamlit as st

In [ ]:
# Cargar el archivo CSV en un DataFrame y dejar columnas 'fecha' y 'demanda'
ruta_csv = '../data/raw/entrenamiento/Evolución de la demanda (B.C.)_01-01-2021_31-12-2024.csv'
df = pd.read_csv(ruta_csv, delimiter=',')
df = df.T.reset_index()
df.columns = ['fecha', 'demanda']
df = df.drop(df.index[0])  # Elimina la fila de encabezado transpuesta
df.head()

                       fecha             demanda
1  2021-01-01T00:00:00+01:00        22753,557734
2  2021-02-01T00:00:00+01:00        19213,729927
3  2021-03-01T00:00:00+01:00        20740,701606
4  2021-04-01T00:00:00+02:00  18915,393747000002
5  2021-05-01T00:00:00+02:00        19296,112439

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 1 to 48
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   fecha    48 non-null     object
 1   demanda  48 non-null     object
dtypes: object(2)
memory usage: 900.0+ bytes

In [35]:
# Limpiar y convertir la columna 'fecha' a tipo datetime, luego a año/mes
fechas = pd.to_datetime(df['fecha'], errors='coerce', utc=True)
df = df[fechas.notna()].copy()
df['fecha'] = fechas[fechas.notna()].dt.strftime('%Y/%m')
df['fecha'] = pd.to_datetime(df['fecha'], format='%Y/%m')
df.head()

       fecha             demanda
1 2020-12-01        22753,557734
2 2021-01-01        19213,729927
3 2021-02-01        20740,701606
4 2021-03-01  18915,393747000002
5 2021-04-01        19296,112439

In [37]:

# Convertir la columna 'demanda' a float con 6 decimales
df['demanda'] = pd.to_numeric(df['demanda'], errors='coerce').round(6)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 1 to 48
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   fecha    48 non-null     datetime64[ns]
 1   demanda  0 non-null      float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 900.0 bytes